name: Lint Code Base
on: 
  push:
    branches: master

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write
      
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      
      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
