name: Lint Code Base
on: 
  push:
    branches: master

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write
      
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      
  pylint:
    runs-on: ubuntu-latest
    name: "pylint"
    steps:
      - uses: davidslusser/actions_python_pylint@v1.0.0
